### ISSUE TITLE
OceanSpy update breaks cutout

### ISSUE THREAD

**Issue by ThomasHaine** [hainegroup/OceanSciences2022#6]
The latest Oceanography image at SciServer with Oceanspy 0.3.3 causes `LLC4320_tutorial_notebook.ipynb` and `LLC_90_Sciserver_tutorial.ipynb` to error with:
<img width="779" alt="image" src="https://user-images.githubusercontent.com/44037162/213814593-ecbb0b49-6369-4f03-aac0-bca96b47013a.png">

**Comment by Mikejmnez** [comment]
The error you get is because `transformation` and `centered` are no longer arguments to `ospy.subsample.cutout`. This must be an old notebook that didn't get updated as I changed how `llc_rearrange.py` transfomed the dataset prior to cutout.

**Comment by ThomasHaine** [comment]
OK. Fixed with update to  [README.md](https://github.com/hainegroup/OceanSciences2022#readme) about drop in long-term support for these notebook versions and transfer of updated, supported notebooks to [Poseidon-share](https://github.com/hainegroup/Poseidon-share).
